FROM node:lts-alpine As build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i

COPY . .

RUN npm run build

FROM node:lts-alpine As prod

ARG NODE_ENV=prod
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i --omit=dev

COPY . .

COPY --from=build /usr/src/app/dist ./dist

CMD ["node", "dist/main"]